# Generated by Django 4.0 on 2022-09-26 12:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personal',
            old_name='tecnologia',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='personal',
            old_name='titulo',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='personal',
            name='edad',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personal',
            name='fecha_alta',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
