# Generated by Django 4.1.1 on 2022-09-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_alter_personal_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='edad',
            field=models.IntegerField(),
        ),
    ]
